VOCAB_DISABLE_DIARIZATION=0 \
VOCAB_DIARIZATION_METHOD=embeddings \
VOCAB_EMB_WIN_SEC=1.8 \
VOCAB_EMB_HOP_SEC=0.6 \
VOCAB_EMB_MIN_RMS=0.008 \
VOCAB_EMB_PITCH_SHIFT=-2 \
VOCAB_ONLY_SMALLEST=1 \
python3 transcription_pipeline.py